# Generated by Django 4.0.2 on 2022-02-27 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 5, 57, 44, 928898, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
