# Generated by Django 4.0.2 on 2022-02-27 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 6, 6, 44, 276953, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
